# Generated by Django 6.0.5 on 2026-07-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_Name', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
