# Generated by Django 6.0.5 on 2026-07-17 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANK', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Address',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='Transcations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('Type', models.CharField(verbose_name=[('debit', 'DEBIT'), ('credit', 'CREDIT')])),
                ('Remaning_Balance', models.CharField(max_length=10)),
                ('From_Acc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related', to=settings.AUTH_USER_MODEL)),
                ('To_Acc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='num', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=14)),
                ('Current_Balance', models.DecimalField(decimal_places=1, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('Created_date', models.DateTimeField(auto_now=True)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='USER_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(verbose_name=[('debit', 'DEBIT'), ('credit', 'CREDIT')])),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
