# Generated by Django 6.0.5 on 2026-08-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANK', '0002_alter_bank_address_transcations_user_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='Type',
            field=models.CharField(verbose_name=[('withdraw', 'WITHDRAW'), ('deposit', 'DEPOSIT')]),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='Current_Balance',
            field=models.FloatField(default=0.0),
        ),
    ]
