# Generated by Django 6.0.5 on 2026-08-03 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANK', '0003_alter_transcations_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='From_Acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related', to='BANK.user_account'),
        ),
        migrations.AlterField(
            model_name='transcations',
            name='To_Acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='num', to='BANK.user_account'),
        ),
    ]
