# Generated by Django 6.0.5 on 2026-08-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BANK', '0004_alter_transcations_from_acc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='Type',
            field=models.CharField(verbose_name=[('withdraw', 'WITHDRAW'), ('deposit', 'DEPOSIT'), ('transfer', 'TRANSFER')]),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='Current_Balance',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=100),
        ),
    ]
