# Generated by Django 6.0.5 on 2026-08-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BANK', '0006_transcations_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcations',
            name='User_id',
        ),
    ]
